CREATE TABLE IF NOT EXISTS table_payments_archive (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    table_id SMALLINT REFERENCES tables(id) ON DELETE CASCADE,
    archived_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_order_price DECIMAL(10,2) NOT NULL
);